"""
Audit completo de integridade do banco — verifica todos os campos
que têm razão de negócio para estar preenchidos.
"""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "backend"))
from database import engine
from sqlalchemy import text

def chk(conn, label, sql):
    n = conn.execute(text(sql)).scalar()
    status = "OK" if n == 0 else f"!! {n} registros"
    print(f"  [{status:>20}]  {label}")
    return n

with engine.connect() as c:

    print("\n=== ORDENS_SERVICO ===")
    tot = c.execute(text("SELECT COUNT(*) FROM ordens_servico")).scalar()
    print(f"  Total: {tot}")
    chk(c, "id_veiculo NULL",      "SELECT COUNT(*) FROM ordens_servico WHERE id_veiculo IS NULL")
    chk(c, "id_empresa NULL",      "SELECT COUNT(*) FROM ordens_servico WHERE id_empresa IS NULL")
    chk(c, "id_contrato NULL",     "SELECT COUNT(*) FROM ordens_servico WHERE id_contrato IS NULL")
    chk(c, "placa NULL",           "SELECT COUNT(*) FROM ordens_servico WHERE placa IS NULL")
    chk(c, "numero_os NULL",       "SELECT COUNT(*) FROM ordens_servico WHERE numero_os IS NULL")
    chk(c, "status_os NULL",       "SELECT COUNT(*) FROM ordens_servico WHERE status_os IS NULL")
    chk(c, "status_execucao NULL", "SELECT COUNT(*) FROM ordens_servico WHERE status_execucao IS NULL")
    chk(c, "responsavel_tec NULL", "SELECT COUNT(*) FROM ordens_servico WHERE responsavel_tec IS NULL")
    chk(c, "fornecedor NULL",      "SELECT COUNT(*) FROM ordens_servico WHERE fornecedor IS NULL")
    chk(c, "tipo_manutencao NULL", "SELECT COUNT(*) FROM ordens_servico WHERE tipo_manutencao IS NULL")
    chk(c, "categoria NULL",       "SELECT COUNT(*) FROM ordens_servico WHERE categoria IS NULL")
    chk(c, "total_os NULL",        "SELECT COUNT(*) FROM ordens_servico WHERE total_os IS NULL")
    chk(c, "km NULL",              "SELECT COUNT(*) FROM ordens_servico WHERE km IS NULL")
    chk(c, "data_entrada NULL",    "SELECT COUNT(*) FROM ordens_servico WHERE data_entrada IS NULL")
    chk(c, "data_execucao NULL",   "SELECT COUNT(*) FROM ordens_servico WHERE data_execucao IS NULL")
    chk(c, "prox_km NULL",         "SELECT COUNT(*) FROM ordens_servico WHERE prox_km IS NULL")
    chk(c, "prox_data NULL",       "SELECT COUNT(*) FROM ordens_servico WHERE prox_data IS NULL")

    print("\n=== OS_ITENS ===")
    tot = c.execute(text("SELECT COUNT(*) FROM os_itens")).scalar()
    tot_pneu = c.execute(text("SELECT COUNT(*) FROM os_itens WHERE sistema='Pneu'")).scalar()
    print(f"  Total: {tot}  |  Pneu: {tot_pneu}")
    chk(c, "os_id NULL",              "SELECT COUNT(*) FROM os_itens WHERE os_id IS NULL")
    chk(c, "sistema NULL",            "SELECT COUNT(*) FROM os_itens WHERE sistema IS NULL")
    chk(c, "servico NULL",            "SELECT COUNT(*) FROM os_itens WHERE servico IS NULL")
    chk(c, "categoria NULL",          "SELECT COUNT(*) FROM os_itens WHERE categoria IS NULL")
    chk(c, "qtd_itens NULL",          "SELECT COUNT(*) FROM os_itens WHERE qtd_itens IS NULL")
    chk(c, "posicao_pneu NULL/Pneu",  "SELECT COUNT(*) FROM os_itens WHERE posicao_pneu IS NULL AND sistema='Pneu'")
    chk(c, "qtd_pneu NULL/Pneu",      "SELECT COUNT(*) FROM os_itens WHERE qtd_pneu IS NULL AND sistema='Pneu'")
    chk(c, "espec_pneu NULL/Pneu",    "SELECT COUNT(*) FROM os_itens WHERE espec_pneu IS NULL AND sistema='Pneu'")
    chk(c, "marca_pneu NULL/Pneu",    "SELECT COUNT(*) FROM os_itens WHERE marca_pneu IS NULL AND sistema='Pneu'")
    chk(c, "modelo_pneu NULL/Pneu",   "SELECT COUNT(*) FROM os_itens WHERE modelo_pneu IS NULL AND sistema='Pneu'")
    chk(c, "manejo_pneu NULL/Pneu",   "SELECT COUNT(*) FROM os_itens WHERE manejo_pneu IS NULL AND sistema='Pneu'")
    chk(c, "condicao_pneu NULL/Pneu", "SELECT COUNT(*) FROM os_itens WHERE condicao_pneu IS NULL AND sistema='Pneu'")

    print("\n=== NOTAS_FISCAIS ===")
    tot = c.execute(text("SELECT COUNT(*) FROM notas_fiscais")).scalar()
    print(f"  Total: {tot}")
    chk(c, "os_id NULL",          "SELECT COUNT(*) FROM notas_fiscais WHERE os_id IS NULL")
    chk(c, "numero_nf NULL",      "SELECT COUNT(*) FROM notas_fiscais WHERE numero_nf IS NULL")
    chk(c, "tipo_nf NULL",        "SELECT COUNT(*) FROM notas_fiscais WHERE tipo_nf IS NULL")
    chk(c, "id_empresa NULL",     "SELECT COUNT(*) FROM notas_fiscais WHERE id_empresa IS NULL")
    chk(c, "fornecedor NULL",     "SELECT COUNT(*) FROM notas_fiscais WHERE fornecedor IS NULL")
    chk(c, "valor_total_nf NULL", "SELECT COUNT(*) FROM notas_fiscais WHERE valor_total_nf IS NULL")
    chk(c, "data_emissao NULL",   "SELECT COUNT(*) FROM notas_fiscais WHERE data_emissao IS NULL")

    print("\n=== NF_ITENS ===")
    tot = c.execute(text("SELECT COUNT(*) FROM nf_itens")).scalar()
    print(f"  Total: {tot}")
    chk(c, "nf_id NULL",            "SELECT COUNT(*) FROM nf_itens WHERE nf_id IS NULL")
    chk(c, "os_item_id NULL",       "SELECT COUNT(*) FROM nf_itens WHERE os_item_id IS NULL")
    chk(c, "quantidade NULL",       "SELECT COUNT(*) FROM nf_itens WHERE quantidade IS NULL")
    chk(c, "valor_unitario NULL",   "SELECT COUNT(*) FROM nf_itens WHERE valor_unitario IS NULL")
    chk(c, "valor_total_item NULL", "SELECT COUNT(*) FROM nf_itens WHERE valor_total_item IS NULL")

    print("\n=== MANUTENCAO_PARCELAS ===")
    tot = c.execute(text("SELECT COUNT(*) FROM manutencao_parcelas")).scalar()
    print(f"  Total: {tot}")
    chk(c, "nf_id NULL",                   "SELECT COUNT(*) FROM manutencao_parcelas WHERE nf_id IS NULL AND deletado_em IS NULL")
    chk(c, "manutencao_id NULL",           "SELECT COUNT(*) FROM manutencao_parcelas WHERE manutencao_id IS NULL AND deletado_em IS NULL")
    chk(c, "nota NULL",                    "SELECT COUNT(*) FROM manutencao_parcelas WHERE nota IS NULL")
    chk(c, "fornecedor NULL",              "SELECT COUNT(*) FROM manutencao_parcelas WHERE fornecedor IS NULL")
    chk(c, "tipo_custo NULL",              "SELECT COUNT(*) FROM manutencao_parcelas WHERE tipo_custo IS NULL")
    chk(c, "valor_item_total NULL",        "SELECT COUNT(*) FROM manutencao_parcelas WHERE valor_item_total IS NULL")
    chk(c, "data_vencimento NULL",         "SELECT COUNT(*) FROM manutencao_parcelas WHERE data_vencimento IS NULL")
    chk(c, "data_venc_original NULL",      "SELECT COUNT(*) FROM manutencao_parcelas WHERE data_vencimento_original IS NULL")
    chk(c, "parcela_atual NULL",           "SELECT COUNT(*) FROM manutencao_parcelas WHERE parcela_atual IS NULL")
    chk(c, "parcela_total NULL",           "SELECT COUNT(*) FROM manutencao_parcelas WHERE parcela_total IS NULL")
    chk(c, "valor_parcela NULL",           "SELECT COUNT(*) FROM manutencao_parcelas WHERE valor_parcela IS NULL")
    chk(c, "forma_pgto NULL",              "SELECT COUNT(*) FROM manutencao_parcelas WHERE forma_pgto IS NULL")
    chk(c, "status_pagamento NULL",        "SELECT COUNT(*) FROM manutencao_parcelas WHERE status_pagamento IS NULL")

    print("\n=== MANUTENCOES ===")
    tot = c.execute(text("SELECT COUNT(*) FROM manutencoes")).scalar()
    print(f"  Total: {tot}")
    chk(c, "id_veiculo NULL",       "SELECT COUNT(*) FROM manutencoes WHERE id_veiculo IS NULL")
    chk(c, "id_empresa NULL",       "SELECT COUNT(*) FROM manutencoes WHERE id_empresa IS NULL")
    chk(c, "id_contrato NULL",      "SELECT COUNT(*) FROM manutencoes WHERE id_contrato IS NULL")
    chk(c, "placa NULL",            "SELECT COUNT(*) FROM manutencoes WHERE placa IS NULL")
    chk(c, "id_ord_serv NULL",      "SELECT COUNT(*) FROM manutencoes WHERE id_ord_serv IS NULL")
    chk(c, "total_os NULL",         "SELECT COUNT(*) FROM manutencoes WHERE total_os IS NULL")
    chk(c, "categoria NULL",        "SELECT COUNT(*) FROM manutencoes WHERE categoria IS NULL")
    chk(c, "fornecedor NULL",       "SELECT COUNT(*) FROM manutencoes WHERE fornecedor IS NULL")
    chk(c, "tipo_manutencao NULL",  "SELECT COUNT(*) FROM manutencoes WHERE tipo_manutencao IS NULL")
    chk(c, "sistema NULL",          "SELECT COUNT(*) FROM manutencoes WHERE sistema IS NULL")
    chk(c, "servico NULL",          "SELECT COUNT(*) FROM manutencoes WHERE servico IS NULL")
    chk(c, "km NULL",               "SELECT COUNT(*) FROM manutencoes WHERE km IS NULL")
    chk(c, "data_execucao NULL",    "SELECT COUNT(*) FROM manutencoes WHERE data_execucao IS NULL")
    chk(c, "responsavel_tec NULL",  "SELECT COUNT(*) FROM manutencoes WHERE responsavel_tec IS NULL")

    print("\n=== REEMBOLSOS ===")
    tot = c.execute(text("SELECT COUNT(*) FROM reembolsos")).scalar()
    print(f"  Total: {tot}")
    chk(c, "id_empresa NULL",         "SELECT COUNT(*) FROM reembolsos WHERE id_empresa IS NULL")
    chk(c, "id_contrato NULL",        "SELECT COUNT(*) FROM reembolsos WHERE id_contrato IS NULL")
    chk(c, "id_cliente NULL",         "SELECT COUNT(*) FROM reembolsos WHERE id_cliente IS NULL")
    chk(c, "id_veiculo NULL",         "SELECT COUNT(*) FROM reembolsos WHERE id_veiculo IS NULL")
    chk(c, "tipo NULL",               "SELECT COUNT(*) FROM reembolsos WHERE tipo IS NULL")
    chk(c, "emissao NULL",            "SELECT COUNT(*) FROM reembolsos WHERE emissao IS NULL")
    chk(c, "vencimento NULL",         "SELECT COUNT(*) FROM reembolsos WHERE vencimento IS NULL")
    chk(c, "valor_reembolso NULL",    "SELECT COUNT(*) FROM reembolsos WHERE valor_reembolso IS NULL")
    chk(c, "status_recebimento NULL", "SELECT COUNT(*) FROM reembolsos WHERE status_recebimento IS NULL")
    chk(c, "recibo NULL",             "SELECT COUNT(*) FROM reembolsos WHERE recibo IS NULL")
    chk(c, "empresa NULL",            "SELECT COUNT(*) FROM reembolsos WHERE empresa IS NULL")
    chk(c, "categoria NULL",          "SELECT COUNT(*) FROM reembolsos WHERE categoria IS NULL")
    chk(c, "descricao NULL",          "SELECT COUNT(*) FROM reembolsos WHERE descricao IS NULL")
    chk(c, "id_ord_serv NULL/Manut",  "SELECT COUNT(*) FROM reembolsos WHERE id_ord_serv IS NULL AND tipo IN ('Manutenção','Franquia de Seguro')")
    chk(c, "numero_os NULL/Manut",    "SELECT COUNT(*) FROM reembolsos WHERE numero_os IS NULL AND tipo IN ('Manutenção','Franquia de Seguro')")
    chk(c, "fatura_mes NULL/Encargo", "SELECT COUNT(*) FROM reembolsos WHERE fatura_mes IS NULL AND tipo='Encargo de Faturamento'")

    print("\n=== FAT_UNITARIO ===")
    tot = c.execute(text("SELECT COUNT(*) FROM fat_unitario")).scalar()
    print(f"  Total: {tot}")
    chk(c, "id_veiculo NULL",  "SELECT COUNT(*) FROM fat_unitario WHERE id_veiculo IS NULL")
    chk(c, "id_empresa NULL",  "SELECT COUNT(*) FROM fat_unitario WHERE id_empresa IS NULL")
    chk(c, "mes NULL",         "SELECT COUNT(*) FROM fat_unitario WHERE mes IS NULL")
    chk(c, "medicao NULL",     "SELECT COUNT(*) FROM fat_unitario WHERE medicao IS NULL")
    chk(c, "trabalhado NULL",  "SELECT COUNT(*) FROM fat_unitario WHERE trabalhado IS NULL")
    chk(c, "parado NULL",      "SELECT COUNT(*) FROM fat_unitario WHERE parado IS NULL")

    print("\n=== CORRETORES ===")
    chk(c, "nome NULL",  "SELECT COUNT(*) FROM corretores WHERE nome IS NULL")
    chk(c, "cnpj NULL",  "SELECT COUNT(*) FROM corretores WHERE cnpj IS NULL")
    chk(c, "susep NULL", "SELECT COUNT(*) FROM corretores WHERE susep IS NULL")

    print("\n=== SEGURO (apólices) ===")
    tot = c.execute(text("SELECT COUNT(*) FROM seguro")).scalar()
    print(f"  Total: {tot}")
    chk(c, "numero_apolice NULL",      "SELECT COUNT(*) FROM seguro WHERE numero_apolice IS NULL")
    chk(c, "seguradora NULL",          "SELECT COUNT(*) FROM seguro WHERE seguradora IS NULL")
    chk(c, "corretor_id NULL",         "SELECT COUNT(*) FROM seguro WHERE corretor_id IS NULL")
    chk(c, "modelo_cobertura NULL",    "SELECT COUNT(*) FROM seguro WHERE modelo_cobertura IS NULL")
    chk(c, "id_empresa NULL",          "SELECT COUNT(*) FROM seguro WHERE id_empresa IS NULL")
    chk(c, "data_inicio NULL",         "SELECT COUNT(*) FROM seguro WHERE data_inicio IS NULL")
    chk(c, "data_fim NULL",            "SELECT COUNT(*) FROM seguro WHERE data_fim IS NULL")
    chk(c, "dia_vencimento NULL",      "SELECT COUNT(*) FROM seguro WHERE dia_vencimento IS NULL")
    chk(c, "valor_total_apolice NULL", "SELECT COUNT(*) FROM seguro WHERE valor_total_apolice IS NULL")
    chk(c, "status_apolice NULL",      "SELECT COUNT(*) FROM seguro WHERE status_apolice IS NULL")

    print("\n=== SEGURO_VEICULO ===")
    tot = c.execute(text("SELECT COUNT(*) FROM seguro_veiculo")).scalar()
    print(f"  Total: {tot}")
    chk(c, "apolice_id NULL",    "SELECT COUNT(*) FROM seguro_veiculo WHERE apolice_id IS NULL")
    chk(c, "id_veiculo NULL",    "SELECT COUNT(*) FROM seguro_veiculo WHERE id_veiculo IS NULL")
    chk(c, "valor_veiculo NULL", "SELECT COUNT(*) FROM seguro_veiculo WHERE valor_veiculo IS NULL")

    print("\n=== SEGURO_MENSAL ===")
    chk(c, "apolice_id NULL", "SELECT COUNT(*) FROM seguro_mensal WHERE apolice_id IS NULL")
    chk(c, "id_veiculo NULL", "SELECT COUNT(*) FROM seguro_mensal WHERE id_veiculo IS NULL")
    chk(c, "id_empresa NULL", "SELECT COUNT(*) FROM seguro_mensal WHERE id_empresa IS NULL")
    chk(c, "vencimento NULL", "SELECT COUNT(*) FROM seguro_mensal WHERE vencimento IS NULL")
    chk(c, "valor NULL",      "SELECT COUNT(*) FROM seguro_mensal WHERE valor IS NULL")

    print("\n=== RASTREAMENTO ===")
    chk(c, "id_veiculo NULL", "SELECT COUNT(*) FROM rastreamento WHERE id_veiculo IS NULL")
    chk(c, "id_empresa NULL", "SELECT COUNT(*) FROM rastreamento WHERE id_empresa IS NULL")
    chk(c, "vencimento NULL", "SELECT COUNT(*) FROM rastreamento WHERE vencimento IS NULL")
    chk(c, "valor NULL",      "SELECT COUNT(*) FROM rastreamento WHERE valor IS NULL")

    print("\n=== DEBITOS_DOCUMENTAIS ===")
    tot = c.execute(text("SELECT COUNT(*) FROM debitos_documentais")).scalar()
    print(f"  Total: {tot}")
    chk(c, "id_veiculo NULL",            "SELECT COUNT(*) FROM debitos_documentais WHERE id_veiculo IS NULL")
    chk(c, "id_empresa NULL",            "SELECT COUNT(*) FROM debitos_documentais WHERE id_empresa IS NULL")
    chk(c, "exercicio NULL",             "SELECT COUNT(*) FROM debitos_documentais WHERE exercicio IS NULL")
    chk(c, "valor_ipva NULL",            "SELECT COUNT(*) FROM debitos_documentais WHERE valor_ipva IS NULL")
    chk(c, "vencimento_ipva NULL",       "SELECT COUNT(*) FROM debitos_documentais WHERE vencimento_ipva IS NULL")
    chk(c, "status_ipva NULL",           "SELECT COUNT(*) FROM debitos_documentais WHERE status_ipva IS NULL")
    chk(c, "valor_licenciamento NULL",   "SELECT COUNT(*) FROM debitos_documentais WHERE valor_licenciamento IS NULL")
    chk(c, "venc_licenciamento NULL",    "SELECT COUNT(*) FROM debitos_documentais WHERE vencimento_licenciamento IS NULL")
    chk(c, "status_licenciamento NULL",  "SELECT COUNT(*) FROM debitos_documentais WHERE status_licenciamento IS NULL")
    chk(c, "ipva_pago s/ data_pgto",     "SELECT COUNT(*) FROM debitos_documentais WHERE status_ipva='Pago' AND data_pgto_ipva IS NULL")
    chk(c, "licenc_pago s/ data_pgto",   "SELECT COUNT(*) FROM debitos_documentais WHERE status_licenciamento='Pago' AND data_pgto_licenciamento IS NULL")

    print("\n=== MULTAS ===")
    tot     = c.execute(text("SELECT COUNT(*) FROM multas")).scalar()
    tot_inf = c.execute(text("SELECT COUNT(*) FROM multas WHERE tipo_multa='Infração'")).scalar()
    tot_nic = c.execute(text("SELECT COUNT(*) FROM multas WHERE tipo_multa='Não Indicação de Condutor'")).scalar()
    print(f"  Total: {tot}  |  Infrações: {tot_inf}  |  NIC: {tot_nic}")
    # Campos obrigatórios
    chk(c, "id_veiculo NULL",        "SELECT COUNT(*) FROM multas WHERE id_veiculo IS NULL")
    chk(c, "id_empresa NULL",        "SELECT COUNT(*) FROM multas WHERE id_empresa IS NULL")
    chk(c, "id_contrato NULL",       "SELECT COUNT(*) FROM multas WHERE id_contrato IS NULL")
    chk(c, "id_cliente NULL",        "SELECT COUNT(*) FROM multas WHERE id_cliente IS NULL")
    chk(c, "ait NULL",               "SELECT COUNT(*) FROM multas WHERE ait IS NULL")
    chk(c, "orgao_emissor NULL",     "SELECT COUNT(*) FROM multas WHERE orgao_emissor IS NULL")
    chk(c, "data_infracao NULL",     "SELECT COUNT(*) FROM multas WHERE data_infracao IS NULL")
    chk(c, "motivo_infracao NULL",   "SELECT COUNT(*) FROM multas WHERE motivo_infracao IS NULL")
    chk(c, "data_limite_indic NULL", "SELECT COUNT(*) FROM multas WHERE data_limite_indicacao IS NULL")
    chk(c, "tipo_multa NULL",        "SELECT COUNT(*) FROM multas WHERE tipo_multa IS NULL")
    chk(c, "data_emissao_m NULL",    "SELECT COUNT(*) FROM multas WHERE data_emissao_multa IS NULL")
    chk(c, "data_vencimento NULL",   "SELECT COUNT(*) FROM multas WHERE data_vencimento IS NULL")
    chk(c, "valor_multa NULL",       "SELECT COUNT(*) FROM multas WHERE valor_multa IS NULL")
    chk(c, "status_multa NULL",      "SELECT COUNT(*) FROM multas WHERE status_multa IS NULL")
    chk(c, "exercicio NULL",         "SELECT COUNT(*) FROM multas WHERE exercicio IS NULL")
    # Desconto por antecipação
    chk(c, "desconto_pct NULL",       "SELECT COUNT(*) FROM multas WHERE desconto_pct IS NULL")
    chk(c, "valor_com_desc NULL",     "SELECT COUNT(*) FROM multas WHERE valor_com_desconto IS NULL")
    # valor_com_desconto deve ser 80% do valor_multa (tolerância de 1 centavo)
    chk(c, "valor_com_desc errado",   "SELECT COUNT(*) FROM multas WHERE ABS(valor_com_desconto - valor_multa * (1 - desconto_pct/100.0)) > 0.01")
    # Se aplicou_desconto=True, valor_pago deve ser igual a valor_com_desconto
    chk(c, "desc aplicado inconsist", "SELECT COUNT(*) FROM multas WHERE aplicou_desconto=1 AND data_pagamento IS NOT NULL AND ABS(valor_pago - valor_com_desconto) > 0.01")
    # Se encargo preenchido, não deve ter desconto aplicado
    chk(c, "encargo + desconto",      "SELECT COUNT(*) FROM multas WHERE aplicou_desconto=1 AND encargo IS NOT NULL AND encargo > 0")
    # Consistência de pagamento
    chk(c, "Pago s/ data_pagamento", "SELECT COUNT(*) FROM multas WHERE status_multa='Pago' AND data_pagamento IS NULL")
    # Regra NIC: toda NIC deve referenciar a original
    chk(c, "NIC s/ multa_origem",    "SELECT COUNT(*) FROM multas WHERE tipo_multa='Não Indicação de Condutor' AND multa_origem_id IS NULL")
    # Regra NIC: valor deve ser 2× a original
    chk(c, "NIC valor != 2x orig",   "SELECT COUNT(*) FROM multas n JOIN multas o ON o.id=n.multa_origem_id WHERE n.tipo_multa='Não Indicação de Condutor' AND ABS(n.valor_multa - o.valor_multa*2) > 0.05")
    # Condutor indicado deve ter nome preenchido
    chk(c, "indicado s/ nome",       "SELECT COUNT(*) FROM multas WHERE condutor_indicado=1 AND nome_condutor IS NULL AND tipo_multa='Infração'")

    print("\n=== FATURAMENTO_MENSAL ===")
    tot = c.execute(text("SELECT COUNT(*) FROM faturamento_mensal")).scalar()
    print(f"  Total: {tot}")
    chk(c, "id_empresa NULL",         "SELECT COUNT(*) FROM faturamento_mensal WHERE id_empresa IS NULL")
    chk(c, "id_contrato NULL",        "SELECT COUNT(*) FROM faturamento_mensal WHERE id_contrato IS NULL")
    chk(c, "id_cliente NULL",         "SELECT COUNT(*) FROM faturamento_mensal WHERE id_cliente IS NULL")
    chk(c, "emissao NULL",            "SELECT COUNT(*) FROM faturamento_mensal WHERE emissao IS NULL")
    chk(c, "vencimento NULL",         "SELECT COUNT(*) FROM faturamento_mensal WHERE vencimento IS NULL")
    chk(c, "valor_locacoes NULL",     "SELECT COUNT(*) FROM faturamento_mensal WHERE valor_locacoes IS NULL")
    chk(c, "status_recebimento NULL", "SELECT COUNT(*) FROM faturamento_mensal WHERE status_recebimento IS NULL")
    chk(c, "empresa (tomador) NULL",  "SELECT COUNT(*) FROM faturamento_mensal WHERE empresa IS NULL")
    # Recebido deve ter valor > 0
    chk(c, "Recebido c/ valor=0",     "SELECT COUNT(*) FROM faturamento_mensal WHERE status_recebimento='Recebido' AND (valor_recebido IS NULL OR valor_recebido=0)")
    # ── Imposto sobre faturamento ──────────────────────────────────────────
    chk(c, "valor_imposto NULL",      "SELECT COUNT(*) FROM faturamento_mensal WHERE valor_imposto IS NULL")
    chk(c, "valor_liquido NULL",      "SELECT COUNT(*) FROM faturamento_mensal WHERE valor_liquido IS NULL")
    chk(c, "status_imposto NULL",     "SELECT COUNT(*) FROM faturamento_mensal WHERE status_imposto IS NULL")
    chk(c, "imposto aliquota errada", "SELECT COUNT(*) FROM faturamento_mensal WHERE aliquota_imposto IS NULL OR aliquota_imposto <= 0")
    chk(c, "imposto > locacoes",      "SELECT COUNT(*) FROM faturamento_mensal WHERE valor_imposto > valor_locacoes")
    chk(c, "liquido != loc-imp",      "SELECT COUNT(*) FROM faturamento_mensal WHERE ABS(valor_liquido - (valor_locacoes - valor_imposto)) > 0.02")

    print("\n=== CONTRATOS ===")
    chk(c, "empresa_id NULL",      "SELECT COUNT(*) FROM contratos WHERE empresa_id IS NULL")
    chk(c, "cliente_id NULL",      "SELECT COUNT(*) FROM contratos WHERE cliente_id IS NULL")
    chk(c, "data_inicio NULL",     "SELECT COUNT(*) FROM contratos WHERE data_inicio IS NULL")
    chk(c, "data_fim NULL",        "SELECT COUNT(*) FROM contratos WHERE data_fim IS NULL")
    chk(c, "status_contrato NULL", "SELECT COUNT(*) FROM contratos WHERE status_contrato IS NULL")

    print("\n=== CONTRATO_VEICULO ===")
    chk(c, "contrato_id NULL", "SELECT COUNT(*) FROM contrato_veiculo WHERE contrato_id IS NULL")
    chk(c, "id_veiculo NULL",  "SELECT COUNT(*) FROM contrato_veiculo WHERE id_veiculo IS NULL")

    print("\n=== FROTA ===")
    chk(c, "id_empresa NULL",      "SELECT COUNT(*) FROM frota WHERE id_empresa IS NULL")
    chk(c, "placa NULL",           "SELECT COUNT(*) FROM frota WHERE placa IS NULL")
    chk(c, "marca NULL",           "SELECT COUNT(*) FROM frota WHERE marca IS NULL")
    chk(c, "modelo NULL",          "SELECT COUNT(*) FROM frota WHERE modelo IS NULL")
    chk(c, "ano_modelo NULL",      "SELECT COUNT(*) FROM frota WHERE ano_modelo IS NULL")
    chk(c, "status NULL",          "SELECT COUNT(*) FROM frota WHERE status IS NULL")
    chk(c, "tipagem NULL",         "SELECT COUNT(*) FROM frota WHERE tipagem IS NULL")
    chk(c, "implemento NULL",      "SELECT COUNT(*) FROM frota WHERE implemento IS NULL")
    chk(c, "tabela_fipe NULL",     "SELECT COUNT(*) FROM frota WHERE tabela_fipe IS NULL")
    chk(c, "valor_implemento NULL","SELECT COUNT(*) FROM frota WHERE valor_implemento IS NULL")
    chk(c, "valor_total NULL",     "SELECT COUNT(*) FROM frota WHERE valor_total IS NULL")

    print("\n=== PNEU_RODIZIOS ===")
    chk(c, "placa NULL",           "SELECT COUNT(*) FROM pneu_rodizios WHERE placa IS NULL")
    chk(c, "data NULL",            "SELECT COUNT(*) FROM pneu_rodizios WHERE data IS NULL")
    chk(c, "km NULL",              "SELECT COUNT(*) FROM pneu_rodizios WHERE km IS NULL")
    chk(c, "posicao_anterior NULL","SELECT COUNT(*) FROM pneu_rodizios WHERE posicao_anterior IS NULL")
    chk(c, "posicao_nova NULL",    "SELECT COUNT(*) FROM pneu_rodizios WHERE posicao_nova IS NULL")
    chk(c, "espec_pneu NULL",      "SELECT COUNT(*) FROM pneu_rodizios WHERE espec_pneu IS NULL")
    chk(c, "marca_pneu NULL",      "SELECT COUNT(*) FROM pneu_rodizios WHERE marca_pneu IS NULL")
    chk(c, "os_ref NULL",          "SELECT COUNT(*) FROM pneu_rodizios WHERE os_ref IS NULL")

    print()
